name: Chocolatine

on:
  push:
    branches-ignore:
      - 'no-ga/**'
  pull_request:
    branches-ignore:
      - 'no-ga/**'

env:

  MIRROR_SSH_URL: "github.com:EpitechPGE1-2025/G-CPE-200-COT-2-1-amazed-26.git"
  EXECUTABLES: "mysh"

jobs:

  check_compilation_and_coding_style:
    if: github.repository != 'EpitechPGE1-2025/G-CPE-200-COT-2-1-amazed-26'
    runs-on: ubuntu-latest
    container: epitechcontent/epitest-docker

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Run coding style checker
        run: banana-check-repo

      - name: Compile project

        run: make

        timeout-minutes: 2

        env:

          CC: epiclang

      - name: Check executables

        run: |
          for exe in $(echo "$EXECUTABLES" | tr ',' ' ')
          do

            if [ ! -f "$exe" ]; then
              echo "$exe not found"
              exit 1
            fi

            if [ ! -x "$exe" ]; then
              echo "$exe not executable"
              exit 1
            fi
          done

      - name: Clean project
        run: make clean


  run_tests:
    needs: check_compilation_and_coding_style
    if: github.repository != 'EpitechPGE1-2025/G-CPE-200-COT-2-1-amazed-26'
    runs-on: ubuntu-latest
    container: epitechcontent/epitest-docker

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Run tests
        run: make tests_run
        timeout-minutes: 2